---
version: 2
plan:
  project-key: MARS
  key: ROCKET
  name: Build the rocket
plan:
  project-key: MARS
  key: SPACESHIP
  name: Build the spaceship
stages:
  - Build hull:
    - Build

Build:
  tasks:
    - script:
      - echo 'Hello World! Changes Added'
