---
version: 2
plan:
  project-key: MARS
  key: ROCKET
  name: Build the rocket
stages:
  - Build:
    - clean
    - install
  - Deploy:
    - clean
    - install

clean:
  tasks:
    - script:
      - echo '--maven clean'
install:
  tasks:
    - script:
      - echo '--maven intsall'
